# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aashay/pcl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aashay/pcl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aashay/pcl/CMakeFiles /home/aashay/pcl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aashay/pcl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named euclid_cluster

# Build rule for target.
euclid_cluster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 euclid_cluster
.PHONY : euclid_cluster

# fast build rule for target.
euclid_cluster/fast:
	$(MAKE) -f CMakeFiles/euclid_cluster.dir/build.make CMakeFiles/euclid_cluster.dir/build
.PHONY : euclid_cluster/fast

#=============================================================================
# Target rules for targets named first_pcl

# Build rule for target.
first_pcl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 first_pcl
.PHONY : first_pcl

# fast build rule for target.
first_pcl/fast:
	$(MAKE) -f CMakeFiles/first_pcl.dir/build.make CMakeFiles/first_pcl.dir/build
.PHONY : first_pcl/fast

#=============================================================================
# Target rules for targets named indices

# Build rule for target.
indices: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 indices
.PHONY : indices

# fast build rule for target.
indices/fast:
	$(MAKE) -f CMakeFiles/indices.dir/build.make CMakeFiles/indices.dir/build
.PHONY : indices/fast

#=============================================================================
# Target rules for targets named planar-seg

# Build rule for target.
planar-seg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 planar-seg
.PHONY : planar-seg

# fast build rule for target.
planar-seg/fast:
	$(MAKE) -f CMakeFiles/planar-seg.dir/build.make CMakeFiles/planar-seg.dir/build
.PHONY : planar-seg/fast

#=============================================================================
# Target rules for targets named range_image

# Build rule for target.
range_image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 range_image
.PHONY : range_image

# fast build rule for target.
range_image/fast:
	$(MAKE) -f CMakeFiles/range_image.dir/build.make CMakeFiles/range_image.dir/build
.PHONY : range_image/fast

#=============================================================================
# Target rules for targets named read_pcd

# Build rule for target.
read_pcd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read_pcd
.PHONY : read_pcd

# fast build rule for target.
read_pcd/fast:
	$(MAKE) -f CMakeFiles/read_pcd.dir/build.make CMakeFiles/read_pcd.dir/build
.PHONY : read_pcd/fast

#=============================================================================
# Target rules for targets named resampling

# Build rule for target.
resampling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 resampling
.PHONY : resampling

# fast build rule for target.
resampling/fast:
	$(MAKE) -f CMakeFiles/resampling.dir/build.make CMakeFiles/resampling.dir/build
.PHONY : resampling/fast

euclid_cluster.o: euclid_cluster.cpp.o
.PHONY : euclid_cluster.o

# target to build an object file
euclid_cluster.cpp.o:
	$(MAKE) -f CMakeFiles/euclid_cluster.dir/build.make CMakeFiles/euclid_cluster.dir/euclid_cluster.cpp.o
.PHONY : euclid_cluster.cpp.o

euclid_cluster.i: euclid_cluster.cpp.i
.PHONY : euclid_cluster.i

# target to preprocess a source file
euclid_cluster.cpp.i:
	$(MAKE) -f CMakeFiles/euclid_cluster.dir/build.make CMakeFiles/euclid_cluster.dir/euclid_cluster.cpp.i
.PHONY : euclid_cluster.cpp.i

euclid_cluster.s: euclid_cluster.cpp.s
.PHONY : euclid_cluster.s

# target to generate assembly for a file
euclid_cluster.cpp.s:
	$(MAKE) -f CMakeFiles/euclid_cluster.dir/build.make CMakeFiles/euclid_cluster.dir/euclid_cluster.cpp.s
.PHONY : euclid_cluster.cpp.s

first_pcl.o: first_pcl.cpp.o
.PHONY : first_pcl.o

# target to build an object file
first_pcl.cpp.o:
	$(MAKE) -f CMakeFiles/first_pcl.dir/build.make CMakeFiles/first_pcl.dir/first_pcl.cpp.o
.PHONY : first_pcl.cpp.o

first_pcl.i: first_pcl.cpp.i
.PHONY : first_pcl.i

# target to preprocess a source file
first_pcl.cpp.i:
	$(MAKE) -f CMakeFiles/first_pcl.dir/build.make CMakeFiles/first_pcl.dir/first_pcl.cpp.i
.PHONY : first_pcl.cpp.i

first_pcl.s: first_pcl.cpp.s
.PHONY : first_pcl.s

# target to generate assembly for a file
first_pcl.cpp.s:
	$(MAKE) -f CMakeFiles/first_pcl.dir/build.make CMakeFiles/first_pcl.dir/first_pcl.cpp.s
.PHONY : first_pcl.cpp.s

indices.o: indices.cpp.o
.PHONY : indices.o

# target to build an object file
indices.cpp.o:
	$(MAKE) -f CMakeFiles/indices.dir/build.make CMakeFiles/indices.dir/indices.cpp.o
.PHONY : indices.cpp.o

indices.i: indices.cpp.i
.PHONY : indices.i

# target to preprocess a source file
indices.cpp.i:
	$(MAKE) -f CMakeFiles/indices.dir/build.make CMakeFiles/indices.dir/indices.cpp.i
.PHONY : indices.cpp.i

indices.s: indices.cpp.s
.PHONY : indices.s

# target to generate assembly for a file
indices.cpp.s:
	$(MAKE) -f CMakeFiles/indices.dir/build.make CMakeFiles/indices.dir/indices.cpp.s
.PHONY : indices.cpp.s

planar-seg.o: planar-seg.cpp.o
.PHONY : planar-seg.o

# target to build an object file
planar-seg.cpp.o:
	$(MAKE) -f CMakeFiles/planar-seg.dir/build.make CMakeFiles/planar-seg.dir/planar-seg.cpp.o
.PHONY : planar-seg.cpp.o

planar-seg.i: planar-seg.cpp.i
.PHONY : planar-seg.i

# target to preprocess a source file
planar-seg.cpp.i:
	$(MAKE) -f CMakeFiles/planar-seg.dir/build.make CMakeFiles/planar-seg.dir/planar-seg.cpp.i
.PHONY : planar-seg.cpp.i

planar-seg.s: planar-seg.cpp.s
.PHONY : planar-seg.s

# target to generate assembly for a file
planar-seg.cpp.s:
	$(MAKE) -f CMakeFiles/planar-seg.dir/build.make CMakeFiles/planar-seg.dir/planar-seg.cpp.s
.PHONY : planar-seg.cpp.s

range_image.o: range_image.cpp.o
.PHONY : range_image.o

# target to build an object file
range_image.cpp.o:
	$(MAKE) -f CMakeFiles/range_image.dir/build.make CMakeFiles/range_image.dir/range_image.cpp.o
.PHONY : range_image.cpp.o

range_image.i: range_image.cpp.i
.PHONY : range_image.i

# target to preprocess a source file
range_image.cpp.i:
	$(MAKE) -f CMakeFiles/range_image.dir/build.make CMakeFiles/range_image.dir/range_image.cpp.i
.PHONY : range_image.cpp.i

range_image.s: range_image.cpp.s
.PHONY : range_image.s

# target to generate assembly for a file
range_image.cpp.s:
	$(MAKE) -f CMakeFiles/range_image.dir/build.make CMakeFiles/range_image.dir/range_image.cpp.s
.PHONY : range_image.cpp.s

read_pcd.o: read_pcd.cpp.o
.PHONY : read_pcd.o

# target to build an object file
read_pcd.cpp.o:
	$(MAKE) -f CMakeFiles/read_pcd.dir/build.make CMakeFiles/read_pcd.dir/read_pcd.cpp.o
.PHONY : read_pcd.cpp.o

read_pcd.i: read_pcd.cpp.i
.PHONY : read_pcd.i

# target to preprocess a source file
read_pcd.cpp.i:
	$(MAKE) -f CMakeFiles/read_pcd.dir/build.make CMakeFiles/read_pcd.dir/read_pcd.cpp.i
.PHONY : read_pcd.cpp.i

read_pcd.s: read_pcd.cpp.s
.PHONY : read_pcd.s

# target to generate assembly for a file
read_pcd.cpp.s:
	$(MAKE) -f CMakeFiles/read_pcd.dir/build.make CMakeFiles/read_pcd.dir/read_pcd.cpp.s
.PHONY : read_pcd.cpp.s

resampling.o: resampling.cpp.o
.PHONY : resampling.o

# target to build an object file
resampling.cpp.o:
	$(MAKE) -f CMakeFiles/resampling.dir/build.make CMakeFiles/resampling.dir/resampling.cpp.o
.PHONY : resampling.cpp.o

resampling.i: resampling.cpp.i
.PHONY : resampling.i

# target to preprocess a source file
resampling.cpp.i:
	$(MAKE) -f CMakeFiles/resampling.dir/build.make CMakeFiles/resampling.dir/resampling.cpp.i
.PHONY : resampling.cpp.i

resampling.s: resampling.cpp.s
.PHONY : resampling.s

# target to generate assembly for a file
resampling.cpp.s:
	$(MAKE) -f CMakeFiles/resampling.dir/build.make CMakeFiles/resampling.dir/resampling.cpp.s
.PHONY : resampling.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... euclid_cluster"
	@echo "... first_pcl"
	@echo "... indices"
	@echo "... planar-seg"
	@echo "... range_image"
	@echo "... read_pcd"
	@echo "... rebuild_cache"
	@echo "... resampling"
	@echo "... euclid_cluster.o"
	@echo "... euclid_cluster.i"
	@echo "... euclid_cluster.s"
	@echo "... first_pcl.o"
	@echo "... first_pcl.i"
	@echo "... first_pcl.s"
	@echo "... indices.o"
	@echo "... indices.i"
	@echo "... indices.s"
	@echo "... planar-seg.o"
	@echo "... planar-seg.i"
	@echo "... planar-seg.s"
	@echo "... range_image.o"
	@echo "... range_image.i"
	@echo "... range_image.s"
	@echo "... read_pcd.o"
	@echo "... read_pcd.i"
	@echo "... read_pcd.s"
	@echo "... resampling.o"
	@echo "... resampling.i"
	@echo "... resampling.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

